### ISSUE TITLE
System.ArgumentException: "Material must not be empty." 

### ISSUE THREAD

**Issue by larakammerer** [bicoom/oom#103]
T4.3: Beim Deserializen wird bei mir anscheinend kein Objekt erstellt, weshalb eine Fehlermeldung bezüglich fehlenden Materials entsteht. Mein .json file schaut aber gut aus. Wo könnte da sonst der Fehler liegen?

**Comment by stefanmaierhofer** [comment]
Bitte Inhalt des .json Files und Konstruktor der problematischen Klasse vergleichen. Gibt es genau einen Konstruktor?  Stimmen die Namen der Argumente mit den Einträgen im .json zusammen? Siehe auch Wiki https://github.com/bicoom/oom/wiki/Lesson-4 für Beschreibung der häufigsten Problemfälle!
