### ISSUE TITLE
how can I add using "System.Windows.Forms;"

### ISSUE THREAD

**Issue by voltae** [bicoom/oom#104]
I like to test the program with a window, but the compiler refuse to add the namespace for the forms.
I found the following [instruction:](https://stackoverflow.com/questions/9646684/cant-use-system-windows-forms), but I don't no where to create the necessary reference to the window. 
`A console application does not automatically add a reference to System.Windows.Forms.dll.
Right-click your project in Solution Explorer and select Add reference... and then find System.Windows.Forms and add it. `

Where are the references to the system libraries inside the project?

**Comment by stefanmaierhofer** [comment]
* inside your project in the solution explorer you should see a "References" folder.
* Right-click on "References" and select "Add Reference ..."
* a dialog window opens
* on the left side navigate to Assemblies/Framework
* check the System.Windows.Forms library
* (you can also use the search field in the top-right corner to narrow down the list of libraries)

**Comment by voltae** [comment]
Thanks for the quick response. I don't see this folder at all, I provide a screenshot. Is it because my visual studio runs on Mac?
<img width="376" alt="solution_explorer" src="https://user-images.githubusercontent.com/36694210/38671936-18865988-3e4d-11e8-92c4-1ff7d35eaccf.png">

**Comment by stefanmaierhofer** [comment]
Ok, you created a .netcore application - things are different there ...
Please create a „Windows Classic“ project (I hope it‘s called classic in vs2017) 😉

**Comment by voltae** [comment]
Well my Visual Studio Community does not support "Windows Classic projects". :-( 
I continue with the .netcore Console Application, it seems I have to switch to Windows, sooner or later.
Thanke you anyway.
