### ISSUE TITLE
T4.1 problem

### ISSUE THREAD

**Issue by frithub** [bicoom/oom#105]
"Adding NUnit...
The 'NUnit 3.10.1' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.7.0'."

MonoDevelop
Version 5.10
Ubuntu 16.04

**Comment by stefanmaierhofer** [comment]
die MonoDevelop version scheint eine alte nuget version zu verwenden.
Man kann probieren eine ältere NUnit version zu intallieren, vermutlich irgendwas mit NUnit 2.***
Falls das auch nicht funktioniert, dann bitte sein lassen.
Newtonsoft.Json funktioniert?
