### ISSUE TITLE
JsonConvert.SerializeObject

### ISSUE THREAD

**Issue by ChristianMoe** [bicoom/oom#37]
Hallo. Kann mir jemand erklären was in dem Beispiel 3 die Befehle machen die mit Json... beginnen? Ich werde daraus leider irgendwie nicht wirklich schlau. Danke.

**Comment by bicoom** [comment]
Bitte ignorieren, das gehört eigentlich zu Beispiel 4.

... und ist im aktuellen Stand des oom Repositories auch bereits entfernt (https://github.com/bicoom/oom/blob/master/lessons/lesson3/lesson3/Program.cs).

**Comment by ChristianMoe** [comment]
Danke. Wie kann ich diese Version eigentlich in mein geforktes Repository rein bekommen? Gibt es hier eine Möglichkeit? Danke.

**Comment by bicoom** [comment]
https://help.github.com/articles/syncing-a-fork/

**Comment by bicoom** [comment]
... das erwähnte "upstream repository" ist die Quelle die man geforkt hat (also mein repository)

**Comment by bicoom** [comment]
... und nicht vergessen vorher den **tip** zu befolgen: https://help.github.com/articles/configuring-a-remote-for-a-fork/

**Comment by bicoom** [comment]
created simple walkthrouh (https://github.com/bicoom/oom/wiki/Walkthrough-Sync-your-Fork)
