### ISSUE TITLE
Git fork with bash commands

### ISSUE THREAD

**Issue by DannyTheFre** [bicoom/oom#39]
CLI output:

 rename {Task2 => tasks/Task2}/Program.cs (100%)
 rename {Task2 => tasks/Task2}/Properties/AssemblyInfo.cs (100%)
 rename {Task2 => tasks/Task2}/Task2.csproj (97%)
Daniels-MacBook-Pro-2:oom Danny$ git status
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
Daniels-MacBook-Pro-2:oom Danny$ git push
Username for 'https://github.com': DannyTheFre
Password for 'https://DannyTheFre@github.com': 
remote: Permission to bicoom/oom.git denied to DannyTheFre.
fatal: unable to access 'https://github.com/bicoom/oom.git/': The requested URL returned error: 403
Daniels-MacBook-Pro-2:oom Danny$ git push
Username for 'https://github.com': DannyTheFre
Password for 'https://DannyTheFre@github.com': 
remote: Permission to bicoom/oom.git denied to DannyTheFre.
fatal: unable to access 'https://github.com/bicoom/oom.git/': The requested URL returned error: 403
Daniels-MacBook-Pro-2:oom Danny$ git remote -v
origin	https://github.com/bicoom/oom.git (fetch)
origin	https://github.com/bicoom/oom.git (push)
Daniels-MacBook-Pro-2:oom Danny$

**Comment by bicoom** [comment]
Hallo,

ich würde den [Sync Walkthrough](https://github.com/bicoom/oom/wiki/Walkthrough-Sync-your-Fork) probieren, aber umgekehrt.

D.h. remote auf eigenes repository definieren
`remote add myrepo https://github.com/DannyTheFre/oom.git`

dann `myrepo` fetchen
`git fetch myrepo`

dann branch `master` in `myrepo` auschecken
`git checkout myrepo/master`

dann lokalen `master` mergen
`git merge master`

dann `myrepo/master` pushen
`git push`



Sollte das nicht funktionieren, dann eigenes repository in einem anderen verzeichnis clonen und die Änderungen (tasks/*) manuell rüberkopieren, commiten, pushen - dann das falsch geclonte Verzeichnis löschen ...

**Comment by bicoom** [comment]
Hat es funktioniert?

**Comment by DannyTheFre** [comment]
Ja, es funktioniert! Vielen Dank!
Am 05.03.2016 17:22 schrieb "bicoom" <notifications@github.com>:
