### ISSUE TITLE
Test läuft nicht wie erwartet

### ISSUE THREAD

**Issue by ChristianMoe** [bicoom/oom#40]
Hallo. Ich habe alles gemäß Walkthrough installiert und einen Test geschriebenb. Wenn ich auf "Alle ausfürhen" klicke, dann tut sich aber leider nichts (siehe Screenshot). Woran kann das liegen? Danke.
[https://www.wetransfer.com/downloads/899acd9810c564c8b94c0f7da9b2a0da20160305141923/8e39ddb98539bce24ef31802ff18d8d520160305141923/f8551a](url)

**Comment by ChristianMoe** [comment]
IN Xamarin wird beim Ausführen angezeigt Task2(laden fehlgeschlagen)

**Comment by bicoom** [comment]
Bei der oben angeführten URL erhalte ich ein "page not found" ...

**Comment by bicoom** [comment]
Beim Walkthrough hat sich leider ein veralteter Testadapter für NUnit eingeschlichen.

Siehe Update: https://github.com/bicoom/oom/wiki/Walkthrough-NUnit

**Comment by bicoom** [comment]
Xamarin Studio: siehe https://github.com/bicoom/oom/issues/41

**Comment by ChristianMoe** [comment]
Hat funktioniert. Danke!
