### ISSUE TITLE
problem with NUnit Version 3.0.1 -- Solved

### ISSUE THREAD

**Issue by gertsch7003** [bicoom/oom#41]
Xamarin Studio doesn't work well with the newes Version of NUnit!

To Solve the problem, a version befor has to be used!

Search in Package Manager for "NUnit version:2.6.4" and install this Version, otherwise some errors appear.

==> Walkthrough was found on this page: 
https://developer.xamarin.com/guides/cross-platform/application_fundamentals/installing-nunit-using-nuget/

(Description why the next versions doesn't work were also found in this Walkthrough)

Kind regards
Gerhard Sabeditsch

PS: I'm working on a MAC

**Comment by bicoom** [comment]
Thanks!

See also updated https://github.com/bicoom/oom/wiki/Walkthrough-NUnit.
