### ISSUE TITLE
Probleme mit Unit Testing bei Xamarin

### ISSUE THREAD

**Issue by amanf** [bicoom/oom#42]
Habe mir NUnit 2.6 runtergeladen, aber ich kann keine Unit Tests starten.

Gehe auf Ansicht > Pads > hört nach PackageConsole auf

**Comment by bicoom** [comment]
Welche Xamarin Version?
* bei Version < 6 -> NUnit 2.6.4
* bei Version == 6 -> NUnit 3.x

Siehe auch https://github.com/bicoom/oom/wiki/Walkthrough-NUnit für korrekte Versionen.

lg

**Comment by amanf** [comment]
Habe <  6 und habe auch NUnit 2.6.4
Kann auch den namespace einbinden (using) und die [Tests] im Code einbauen.
Aber die Buttons fehlen.

**Comment by bicoom** [comment]
Wäre es möglich einen Screenshot zu bekommen (auch gerne per Mail).
Ich kann mir das gerade nicht wirklich vorstellen (bei mir ist bei Pads der Eintrag PackageConsole an vorletzter Stelle und "Unit Tests" ca. in der Mitte - d.h. "hört nach PackageConsole auf" ergibt für mich keinen Sinn ;-)

"Aber die Buttons fehlen." - Welche Buttons? Sieht man den Unit Test Tab und dort gibt es keinen "Run All" Button? Oder sind mit "Buttons" die Menueinträge in View/Pads gemeint?

Und noch einmal die Bitte:
Welche Xamarin Version? Im Menu -> Help/About - dort sieht man die genaue Version.
(bei mir ist das z.B. Version 6.0 (build 4520))

Englisch oder Deutsch?

Gibt es unter "Help/Check for Updates" neuere Versionen?

lg

**Comment by amanf** [comment]
https://drive.google.com/file/d/0B2IbLBwnGZ1CV2ppRG9VSndWR3M/view?usp=sharing

Version 5.10

MfG,
Alexander Manafi

**Comment by bicoom** [comment]
! Gibt es unter "Help/Check for Updates" neuere Versionen?

;-)

**Comment by bicoom** [comment]
Schon einmal neu installiert?

**Comment by bicoom** [comment]
Windows oder MacOS?

**Comment by amanf** [comment]
Linux Ubuntu, neuere versionen gibt es nicht und ich werds einfach mal
neuinstallieren. MfG, Alexander Manafi
Am 07.03.2016 16:59 schrieb "bicoom" <notifications@github.com>:

**Comment by christoph312** [comment]
unter linux mus man zusätzlich das paket "monodevelop-nunit" installieren, damit das unit testing verfügbar ist.

**Comment by amanf** [comment]
super, danke!!


Mit freundlichen Grüßen,
Alexander Manafi

Am 8. März 2016 um 01:00 schrieb Christoph <notifications@github.com>:

**Comment by bicoom** [comment]
Danke! :-)
