### ISSUE TITLE
NUnit Testprobleme 

### ISSUE THREAD

**Issue by rkerschbaumer** [bicoom/oom#44]
bei starten des Testdurchlaufs tritt ein Internal-Error auf: "UnsupportedFrameworkException: Skipped loading assembly Task4 because it references an unsupported verrsion of the nunit.framework, 3.0.5813.39031"
- nach update auf 3.2 selbe Fehlermeldung
- Installieren des Pakets NUnit.AddinsDependencies_v2-6-4

**Comment by bicoom** [comment]
Visual Studio oder Xamarin?
Falls Xamarin, welche Version?

Paket NUnit.AddinsDependencies_v2-6-4 wird nicht gebraucht.

Siehe https://github.com/bicoom/oom/wiki/Walkthrough-NUnit für korrekte Versionen.

lg

**Comment by rkerschbaumer** [comment]
Ich verwende Xamarin, das Problem hab' ich gestern Abend dann noch fixen können, durch installieren der 2.6.4 Version von NUnit.
