### ISSUE TITLE
[BUG] Ausgabe von Deseralize-Objekten nicht möglichen

### ISSUE THREAD

**Issue by WolfgangWeissinger** [bicoom/oom#46]
Bei der Ausgabe des wieder eingelesenen Json-String wird das Programm ohne Probleme erstellt, sobald die Ausführung zur Zeile 29 kommt erscheint aber die unten angeführte Fehlermeldung.

Quellcode:
`23            var c = new RentalObjects_bouncer("SkyKids", 73, 79, 119, 20);
24
25            var a = JsonConvert.SerializeObject(c);
26            Console.WriteLine(a);
27
28            
29            RentalObjects_bouncer b = JsonConvert.DeserializeObject<RentalObjects_bouncer>(a);
30            Console.WriteLine(b.prop_name);
31            Console.WriteLine(b.prop_price_weekdays);`

Fehlermeldung:
> {"prop_name":"SkyKids","prop_price_weekdays":73.0,"prop_price_weekends":79.0,"prop_price_48h":119.0,"prop_weight":0}
> 
> Unbehandelte Ausnahme: System.Exception: Namensfeld ist leer
>    bei task3._1.RentalObjects_bouncer..ctor(String newname, Double newprice_weekdays, Double newprice_weekends, Double newprice_48h, Int32 newweight) in C:\Users\Lenovo-User\oom\tasks\task4\task4\Class1.cs:Zeile 90.
>    bei Void .ctor(System.String, Double, Double, Double, Int32)(Object[] )
>    bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
>    bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
>    bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    bei Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    bei Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    bei Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>    bei Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
>    bei task3._1.Program.Main(String[] args) in C:\Users\Lenovo-User\oom\tasks\task4\task4\Program.cs:Zeile 29.

**Comment by stefanmaierhofer** [comment]
Json.net serialisiert alle public Properties und versucht beim deserialisieren die Namen den Argumenten des Constructors zuzuordnen. Wenn diese anders heissen kann das fehlschlagen.

**Comment by hpartmann** [comment]
Ich hatte das Problem auch - aber interessant ist das Groß und Kleinschreibung nicht berücksichtigt werden - wie in Lesson 4; das hat mich dann leider etwas verwirrt und ich dachte das die Argumente des Konstruktors und die Properties verschiedene Namen haben müssen !
