### ISSUE TITLE
Wie kann ich ein in C# ein Flexibles Array anlegen?

### ISSUE THREAD

**Issue by ChristianMoe** [bicoom/oom#49]
Hallo, ich habe bei mir die Klasse Consultant in meinem Beispiel. Jeder Consultant hat nun 1 bis x Qualifikationen. ich hätte versucht ein Array anzulegen in meinem Code und zwar so, dass es mit UpdateQualification flexibel geändert/ergänzt werden kann. oder wäre der Ansatz besser eine eigene Klasse Qualifikationen zu erstellen und dann verschiedene Instanzen dieser Klasse den verschiedenen Consultants zuzuweisen? Wenn ja, wie kann ich Instanzen einer Klasse einer Instanz einer anderen Klasse zuweisen? Danke.

**Comment by bicoom** [comment]
Hallo,

[`List<T>`](https://msdn.microsoft.com/library/6sh2ey19(v=vs.110).aspx) ist ein flexibles Array, z.B.

```C#
class Consultant
{
    List<Qualification> m_qualifications = new List<Qualification>();
    
    public void AddQualification(Qualification x) { m_qualifications.Add(x); }
    public bool HasQualification(Qualification x) { return m_qualifications.Contains(x); }
    public void RemoveQualification(Qualification x) { m_qualifications.Remove(x); }
    ....
}
```

Alternativ, wenn die Ordnung keine Rolle spielt eignet sich z.B. auch [`HashSet<T>`](https://msdn.microsoft.com/library/bb359438(v=vs.110).aspx).

Wichtig bei allen Varianten ist immer, dass man immer das selbe Objekt verwendet und nicht immer neue Objekte erzeugt die eigentlich das selbe "Ding" repräsentieren, d.h.

```C#
var a = new Qualification("OO-Programming");
var b = new Qualification("OO-Programming");
// a != b, d.h. es funktioniert nicht folgendes:
var x = new Consultant();
x.AddQualification(a);
x.RemoveQualification(b);
// x hat immer noch qualification a
```

**Comment by ChristianMoe** [comment]
Danke. Soweit habe ich das nun geschafft. Gibt es auch eine Einfache Möglichkeit das dann in Json zu serialisieren? Ich habe es ja im Json Constructor leider nicht abgebildet. Danke.

**Comment by bicoom** [comment]
Man kann Listen (oder Arrays, etc.) einfach (de)serialisieren, z.B.

```C#
List<Book> books = ...;
var s = JsonConvert.SerializeObject(books);
var books2 = JsonConvert.DeserializeObject<List<Book>>(s)
```

**Comment by bicoom** [comment]
added issue to https://github.com/bicoom/oom/wiki/FAQ
