### ISSUE TITLE
"T1.6" might not be a very good name for a solution 

### ISSUE THREAD

**Issue by mriedmann** [bicoom/oom#5]
Based on this MSDN page (https://msdn.microsoft.com/en-us/library/893ke618(v=vs.71).aspx) I would recommend renaming all solutions to something like "T1_6" or "T16".

In my understanding dot in namespace-names is reserved to some kind of delemiter between different modules, features or classes and should not be used as part of a solution- or project-name.

**Comment by bicoom** [comment]
renamed T1.6 to Task1
renamed T2 to Task2
updated screenshots in Walkthrough Hello World
