### ISSUE TITLE
problem mit lesson6 -- keine ausgabe auf konsole

### ISSUE THREAD

**Issue by gertsch7003** [bicoom/oom#50]
Ich habe bei lesson6 ein Problem mit der Ausgabe:

Ich verwende Xamarin 5.10.3 (build 27) auf einem MAC (10.11.2)

Bei der Programm Klasse habe ich Ihre auskommentierte Zeile wieder nicht auskommentiert

`PushExample.Run();`

Und diese Zeile auskommentiert:
`//TasksExample.Run();`

den Rest habe ich ident gelassen.

Ich erwarte mir, dass auf der Konsole meine Mausbewegungen als X und Y Parameter sichtbar werden, dass tun sie leider nicht.

ich habe auch in der Methode PushExample.Run() 
bei  .Subscribe(e => System.Console.WriteLine($"[C] ({e.X}, {e.Y})"))

System.Console. nachtragen müssen obwohl es im 

using static System.Console;

eigentlich nicht mehr notwendig gewesen wäre. Xamarin meinte aber, dass WriteLine nicht existiert.

Zum Verhalten:
Das gewünschte Fenster öffnet sich, nur leider gibt mir die Console keinen Text aus.

Mit freundlichen Grüßen
Gerhard Sabeditsch

**Comment by bicoom** [comment]
Hallo,

leider kann ich die Probleme unter Windows nicht reproduzieren :-(
Ich habe exakt die selbe Version (5.10.3, build 27) installiert, aber bei mir treten die beschriebenen Probleme nicht auf. Allerdings kann ich mich erinnern, dass ich das Problem mit Console.WriteLine mit einer älteren Xamarin-Version vor ein paar Monaten auch unter Windows hatte ...

Ich würde deshalb noch ausprobieren auf die aktuellste Alpha-Version von Xamarin Studio upzugraden:
Im Menu: Help/Check for Updates -> auf Alpha Channel umschalten, dort müsste es dann eine Version 6.... zu installieren geben.

lg

**Comment by bicoom** [comment]
Help Wanted :-)
Gibt es Mac-User die das Problem reproduzieren können, bzw. bei denen es nicht auftritt?

**Comment by stefanmaierhofer** [comment]
see #54
