### ISSUE TITLE
lesson 4: add/improve explanation for json-constructors

### ISSUE THREAD

**Issue by hpartmann** [bicoom/oom#52]
Die Argumente des JSON Konstruktors und die Properties müssen beim Serialisieren und Deserialisieren aufgrund eines bugs die gleichen Namen haben
siehe: "[BUG] Ausgabe von Deseralize-Objekten nicht möglichen #46"
Ich dachte das aufgrund der Groß und Kleinschreibung in Lesson 4 genau das Gegenteil - das die Namen verschieden sein müssen ... vielleicht kann man da zukünftig einen Kommentar in die Lesson 4 einfügen bzw. die Namen alle gleich wählen ?
mfg - Harald Partmann

**Comment by bicoom** [comment]
https://github.com/bicoom/oom/wiki/Lesson-4
