### ISSUE TITLE
Interner Fehler bei Unit Test

### ISSUE THREAD

**Issue by BabsiL** [bicoom/oom#88]
Ich habe NUnit genauso wie in der Beschreibung hinzugefügt und bekomme schon beim allerersten Test (public void Simple test...) diese Fehlermeldung:

UnsupportedFrameworkException: Skipped loading assembly Task2 because it references an unsupported version of the unit.framework, 3.2.1.0 

Ob ich (1==1) oder (1==2) eingebe ist egal, ich bekomme immer nur diese Meldung, erfahre aber nicht ob der Test durchgeht oder fehlschlägt

**Comment by bicoom** [comment]
Anscheinend passt die Versionen von NUnit nicht zum Projekt. Bis zum Ausführen von Tests kommt es deshlab garnicht - deshalb macht es auch keinen Unterschied ob 1 == 1 oder 1 == 2 :-)

Unter welcher Entwicklungsumgebung läuft das? Visual Studio oder Xamarin?
Falls Xamarin: welche Version?

lg

**Comment by BabsiL** [comment]
danke für die schnelle antwort:)

ich habe xamarin am mac
die version ist 5.10.3(buid 51)

**Comment by bicoom** [comment]
Möglicherweise hilft es ein älteres NUnit-Paket zu installieren (2.6.4).
Siehe auch https://github.com/bicoom/oom/issues/44

Falls das auch nicht funktioniert, dann einfach sein lassen ;-)

**Comment by BabsiL** [comment]
Mit 2.6.4 ist dieser fehler weg, dafür dafür gibts aber einen anderen internen fehler..
"RemotingException: Unix transport error."

**Comment by bicoom** [comment]
Ok, der ist sogar für mich neu ;-)
Bitte die Unit-Tests gut sein lassen!

lg

**Comment by BabsiL** [comment]
okay mach ich, danke:)
