### ISSUE TITLE
Hilfe bei Rx Multithreading

### ISSUE THREAD

**Issue by mriedmann** [bicoom/oom#89]
Ich habe versucht meinen Multi-Threading Code durch Rx-Time/Interval zu ersetzen, was mir bei einigen Punkten gelungen ist. Zu mehr als das https://github.com/mriedmann/oom/blob/master/tasks/Task2/Task2/Program.cs#L107 habe ich das Teil aber leider nicht überreden können. 

**Was ich mir vorstelle:**
- Console-Thread soll x Timer (pro Server einen) anlegen.
- In jedem Timer-Thread soll maximal alle x Sekunden eine Klassenmethode ausgeführt werden
- Nach Timer/Methoden-Abschluss soll ein "Drawer" im Main-Thread benachrichtigt werden
- Dieser soll die entsprechenden Infos der Klasse in den Display-Buffer schreiben 
- alle x Sekunden (durch Throttle) soll der "Drawer" außerdem einen refresh der GUI durchführen. 

**Woran es gescheitert ist:**
- Wie implementiere ich einen "Timer" in Rx richtig? Habe viele verschiedene Möglichkeiten gefunden, keine hat so funktioniert, wie ich das erwartet hätte.
- Wie ist mit Thread-Übergreifenden Benachrichtigungen zu verfahren? Auf was achten? Wie genau Implementieren?
- Gibt es eine einfache Möglichkeit die von Rx erstellten Threads/Tasks zeitweilig zu synchronisieren/blocken?
- Aktuelle, ausführliche Doku zu Rx? Habe viel veraltetes und sehr oberflächliches gefunden. 

**Allgemein:**
Ist das was ich mir da vorstelle mit Rx möglich bzw. vorgesehen oder grenzt das schon an Zweckentfremdung? Ohne Rx mit klassischen Tasks ist das alles zwar nicht schön (enge Kopplung) aber auch nicht wirklich schwer => Lohnt der Aufwand?

Danke!

**Comment by bicoom** [comment]
Hallo,

 

kurze Antwort da ich seit einer Stunde unterwegs sein sollte ;-)

 

Ich habe eine alternative Implementierung erstellt (siehe Attachment) welche einige der Fragen beantwortet.

 

Allgemeine Punkte:

* für die konkrete Anwendung sind beide Varianten meiner Meinung nach gleichwertig („Lohnt der Aufwand?“) – die Frage ist letztlich eher „will ich ein imperatives oder ein funktionales Design meines Systems“ …   

* ein funktionales Design spielt dann seine Vorteile aus wenn ich statt der derzeit sehr einfachen processing pipeline ein viel komplexeres processing habe und/oder ich viele verschiedene Bausteine (immer wieder neu) composen will , z.B. mit vielen verschiedenen Streams für verschiedene Zwecke, verschiedenen Filtern, vielleicht dynamisch konfigurierbar, vielleicht Millionen von Items statt 4 wo ich vielleicht plötzlich horizontal scaling auf einen Cluster von Maschinen machen muss, etc. – wenn ich in diese Richtung gehe dann wird der imperative Ansatz plötzlich sehr sehr schnell sehr sehr unübersichtlich, komplex und wahnsinnig schwer zu testen, zu ändern und überhaupt korrekt zu implementieren …

* Rx dient letztlich nur als einfach verfügbare Implementierung mit der man schnell etwas herzeigen kann und auch schön auf bereits vorhandene Erfahrungen mit pull sequences (IEnumerables) aufbauen kann – die grundsätzliche Entscheidung ein System funktional zu designen hat nichts mit Rx zu tun …

* Synchronisation ist ein komplett separates Problem. Grundsätzlich ist ein asynchrones und/oder paralleles Design mit mutable shared State (und dadurch notwendiger Synchronisation) nicht vereinbar - ich kann bei realistisch komplexen Systemen nur entweder das eine oder das andere haben.

* d.h. wenn man das Projekt weiter in Richtung „funktionales Design“ umbaut (um die „lock“ statements zu eliminieren), müsste man als nächstes die Datenstrukturen (Server, etc.) immutable machen (sogenannte persistente Datenstrukturen, https://en.wikipedia.org/wiki/Persistent_data_structure) – bei so einem Design erzeugt jede Änderung eines Objekts eine logische Kopie des Objekts (mit der Änderung) – d.h. es gibt keinen mutable state mehr und damit keinen Grund mehr für Synchronisation (und keine Möglichkeit mehr Deadlocks oder Race Conditions zu produzieren) – natürlich tausche ich das wieder gegen andere Nachteile ein die allerdings im Vergleich viel einfacher zu beherrschen sind.

 

Bitte gerne weitere Fragen, ich finde zwischendurch sicher immer wieder mal Zeit ;-) 

 

Liebe Grüße,

Stefan Maierhofer

**Comment by bicoom** [comment]
[20160609.txt](https://github.com/bicoom/oom/files/306442/20160609.txt)
