### ISSUE TITLE
Brauche Hilfe bei Console Readline

### ISSUE THREAD

**Issue by BabsiL** [bicoom/oom#91]
Ich habe Sie eh schon nach der vorletzten und letzten Stunde deshalb gefragt, ich will eigentlich nur einen Wert einlesen, mit einer Funktion verändern und wieder ausgeben. Aber irgendwie bekomme ich es nicht hin dass man etwas eingeben kann, Nach Console Readline wartet das Programm nicht auf eine Eingabe, sondern macht einfach weiter.
Ich habe eh auskommentiert was ich machen will und zwar in der Main (aufrufen) und in Lebensmittel.cs (Funktionen). Die eine Funktion habe ich auch im Interface (Produkte)

**Comment by stefanmaierhofer** [comment]
der folgende Code aus ihrem Projekt funktioniert bei mir wie gewünscht:

```
Console.WriteLine("neue Artikelnummer eingeben: \n");
int neuenummer = Int32.Parse(Console.ReadLine());
x.Artikelnummern_aktualisieren(neuenummer);
```

d.h. Console.ReadLine blockiert bis etwas eingegeben wird, danach läuft das Programm weiter.

Vielleicht gibt es ein Problem mit der Console wenn man das Programm aus dem Xamarin-Studio heraus startet?! Sie könnten probieren direkt das Task2.exe (ohne Xamarin-Studio) zu starten.
