### ISSUE TITLE
Lesson3 interface usage

### ISSUE THREAD

**Issue by cop1492** [bicoom/oom#92]
When using interface keyword instead abstract when defining a parent object, in the inheriting object it is not possible to "override" methods. Since you can not define methods with overloads or body in the interface, there also is no need to try it. Any ide gives the hint or error not to find a matching method in the parent when using override.

So for me it seems to be not correct to use it like:

Interface Ixy { 
Void print ();
}

Void z (var param) : Ixy {
void override print (){statement;};
}

Please excuse any unaccuracy in writing code as I do it in the metro on my mobile.

I would appreciate a short statement on this.
Kind regards!

**Comment by cop1492** [comment]
The correct usage as I understand and daily use it would be without trying to override it. 

The interface just "tells" the inheriting object that there is the need of a method but nothing else.

**Comment by bicoom** [comment]
You are completely right!
I think the following StackOverflow article nicely explains all the finer details:
http://stackoverflow.com/questions/3621410/why-are-c-sharp-interface-methods-not-declared-abstract-or-virtual

**Comment by cop1492** [comment]
eventually it would be good to adopt the Lesson 3 - code as follows(?):
**FROM:**

`interface A
{
    void Print();
}

class B : A
{
    public override void Print()
    {
        Console.WriteLine("I am a B!");
    }
}

class C : A
{
    public override void Print()
    {
        Console.WriteLine("I am a C!");
    }
}

...

// A x = new A(); // not possible, interfaces can't be instantiated
A y = new B();
A z = new C();

//x.Print();
y.Print();
z.Print();
Output:
I am a B!
I am a C!`

**TO:**
`
interface A
{
    void Print();
}

class B : A
{
    public void Print()
    {
        Console.WriteLine("I am a B!");
    }
}

class C : A
{
    public void Print()
    {
        Console.WriteLine("I am a C!");
    }
}

...

// A x = new A(); // not possible, interfaces can't be instantiated
A y = new B();
A z = new C();

//x.Print();
y.Print();
z.Print();
Output:
I am a B!
I am a C!
`

**Comment by bicoom** [comment]
done
