### ISSUE TITLE
Appveyor walkthrough

### ISSUE THREAD

**Issue by seekaddo** [bicoom/oom#94]
I have been trying to figure out how to automate testing with the [Appveyor](https://www.appveyor.com/) but having problem with the yaml configuration file. Would it be possible for us to get a simple walkthrough on how to test c# code with a simple yaml configuration for the Appveyor? It will be really helpful. The main problem is with the .ymal configuration, what to include and how it works.

greetings

**Comment by bicoom** [comment]
https://github.com/bicoom/oom/wiki/Walkthrough-AppVeyor

hope this helps!

**Comment by seekaddo** [comment]
Yea, Thanks
