### ISSUE TITLE
Task 4 - Komponetentest deaktivieren

### ISSUE THREAD

**Issue by ic16b089** [bicoom/oom#95]
Können Sie mir bitte einen Tipp geben wie ich in Xamarin die Komponententests deaktivieren kann so dass wieder eine Konsolenfenster zu interaktiven Eingaben beim Ausführen kommt.

Vielen Dank

**Comment by bicoom** [comment]
View -> Pads -> Application Output

??

**Comment by ic16b089** [comment]
Vielen Dank!
Funktioniert 😊
