### ISSUE TITLE
push verweigert

### ISSUE THREAD

**Issue by voltae** [bicoom/oom#97]
nach Eingabe von git push und usernamen und pass kommt bei mir folgende Meldung:
remote: Permission to bicoom/oom.git denied to voltae.
```fatal: unable to access 'https://github.com/bicoom/oom.git/': The requested URL returned error: 403```
Ich hab schon mit inkorrektem Password probiert, da kommt dann:
remote: Invalid username or password.
```fatal: Authentication failed for 'https://github.com/bicoom/oom.git/'```

**Comment by bicoom** [comment]
push auf das original Repository https://github.com/bicoom/oom.git/ funktioniert nicht, da habe nur ich entsprechende Rechte.

Bitte zuerst das Repository forken (Task 1.4) und dann das eigene (geforkte) Repository clonen (Task 1.5) und damit arbeiten. Hier funktioniert dann auch push!

**Comment by voltae** [comment]
Danke, ja ich hab bei falschen Projekt herumgewerkelt, und mich gewundert, warum ich nix verändern kann. Hätte mir eigentlich bei der falschen URL auffallen sollen. Jetzt ist es mir klar. Schönes Wochenende!
