### ISSUE TITLE
Currency Newtonsoft.Json.Linq funzt nicht

### ISSUE THREAD

**Issue by christinauhl** [bicoom/oom#98]
Die Währungs-Umrechnung funktioniert bei mir im Beispiel Books nicht, Ideen warum das so ist?
<img width="913" alt="bildschirmfoto 2018-03-02 um 18 53 37" src="https://user-images.githubusercontent.com/36789998/36913814-628053a8-1e4b-11e8-977f-29a1d126894f.png">

**Comment by bicoom** [comment]
Es sieht so aus als ob das Newtonsoft.Json package nicht installiert ist.
Visual Studio macht das automatisch, falls nicht dann rechte Maustaste auf Solution "lesson2" und "Restore Nuget Packages" auswählen.
Bei anderen Entwicklungsumgebungen am einfachsten nach "NameDerEntwicklungsumgebung" und "nuget package restore" googlen.

**Comment by stefanmaierhofer** [comment]
Ist das Problem gelöst?
